/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Robert' at '2/14/17 12:42 PM' with Gradle 2.14.1
 *
 * @author Robert, @date 2/14/17 12:42 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
